name: Compile Latex and Release PDF  


on: 
  push:
    branches:
      - main
      
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Delete
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 1
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Compilation
        uses: vinay0410/tectonic-action@master
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tex_path: 'Mathematics/2nd/Numerical_methods/Numerical_methods.tex'
          push: 'yes'
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload asset to release
        uses: csexton/release-asset-action@v2
        with:
          release-url: ${{ steps.create_release.outputs.upload_url }}
          files: Numerical_methods.pdf
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Remove File
        uses: JesseTG/rm@v1.0.2
        with:
          path: Mathematics/2nd/Numerical_methods/Numerical_methods.pdf
