name: Compile Latex and Release PDF  


on: 
  push:
    branches:
      - main
      
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Delete
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 1
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            main.tex
            Mathematics/1st/Fundamentals_of_mathematics/Fundamentals_of_mathematics.tex
      - name: Pushes test file
        uses: dmnemec/copy_file_to_another_repo_action@v1.0.4
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'main.pdf'
          destination_repo: 'victorballester7/victorballester7.github.io'
          destination_folder: 'Mathematics'
          user_email: 'victor.ballester.ribo@gmail.com'
          user_name: 'victorballester7'
          destination_branch: 'main'
