name: Compile Latex and Release PDF  


on: 
  push:
    branches:
      - main
      
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Delete
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 1
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Compile - main
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex  
      - name: Compile - FM
        uses: xu-cheng/latex-action@v2
        with:
          root_file: Fundamentals_of_mathematics.tex
          working_directory: Mathematics/1st/Fundamentals_of_mathematics/ 
      - name: Compile - LA
        uses: xu-cheng/latex-action@v2
        with:
          root_file: Linear_algebra.tex
          working_directory: Mathematics/1st/Linear_algebra/   
      - name: Compile - RVF
        uses: xu-cheng/latex-action@v2
        with:
          root_file: Real-valued_functions.tex
          working_directory: Mathematics/1st/Real-valued_functions/ 
      - name: Compile - AS
        uses: xu-cheng/latex-action@v2
        with:
          root_file: Algebraic_structures.tex
          working_directory: Mathematics/2nd/Algebraic_structures/   
      - name: Compile - FOSV
        uses: xu-cheng/latex-action@v2
        with:
          root_file: Functions_of_several_variables.tex
          working_directory: Mathematics/2nd/Functions_of_several_variables/ 
      - name: Compile - LG
        uses: xu-cheng/latex-action@v2
        with:
          root_file: Linear_geometry.tex
          working_directory: Mathematics/2nd/Linear_geometry/   
      - name: Compile - MA
        uses: xu-cheng/latex-action@v2
        with:
          root_file: Mathematical_analysis.tex
          working_directory: Mathematics/2nd/Mathematical_analysis/   
      - name: Compile - NM
        uses: xu-cheng/latex-action@v2
        with:
          root_file: Numerical_methods.tex
          working_directory: Mathematics/2nd/Numerical_methods/
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload asset to release
        uses: csexton/release-asset-action@v2
        with:
          release-url: ${{ steps.create_release.outputs.upload_url }}
          files: |
            main.pdf
            Mathematics/1st/Fundamentals_of_mathematics/Fundamentals_of_mathematics.pdf
            Mathematics/1st/Linear_algebra/Linear_algebra.pdf
            Mathematics/1st/Real-valued_functions/Real-valued_functions.pdf
            Mathematics/2nd/Algebraic_structures/Algebraic_structures.pdf
            Mathematics/2nd/Discrete_mathematics/Discrete_mathematics.pdf
            Mathematics/2nd/Functions_of_several_variables/Functions_of_several_variables.pdf
            Mathematics/2nd/Linear_geometry/Linear_geometry.pdf
            Mathematics/2nd/Mathematical_analysis/Mathematical_analysis.pdf
            Mathematics/2nd/Numerical_methods/Numerical_methods.pdf
          github-token: ${{ secrets.GITHUB_TOKEN }}